config/routes.rb
Rails.application.routes.draw do
  root "songs#index"

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :songs, :places
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, length: { minimum: 1 }, presence: true

  belongs_to :user

  def self.filter(current_user, sort = 'title')
    where(user_id: current_user.id)

    case sort
    when 'artist'
      order(:artist)
    when 'recent'
      order(created_at: :desc)
    else
      order(:title)
    end
  end

  def save_lyrics
    test = HTTParty.get(lyrics_url)
    html = test.body

    document = Nokogiri::HTML(html)
    spaced = document.css('br').each{ |br| br.replace("\n") }
    lyrics = spaced.xpath("//div[contains(@class, 'Lyrics__Container')]")

    update(lyrics: lyrics.text)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:destroy, :edit, :update, :show]

  def index
    search_term = params[:input]
    response = HTTParty.get("https://api.genius.com/search?q=#{search_term}&access_token=#{ENV["GENIUS_CLIENT_TOKEN"]}", format: :plain)
    @result = JSON.parse response, symbolize_names: true

    return if current_user.nil?

    @songs = Song.filter(current_user, params[:sort])
    @song = current_user.songs.build
  end

  def new
    @song = Song.new
  end

  def show
  end

  def create
    @song = current_user.songs.build(song_params)

    if @song.save
      @song.save_lyrics
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @song.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def song_params
    params.require(:song).permit(:artist, :artist_url, :title, :genius_id, :lyrics_url, :image_url)
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_search.html.erb
<%= form_with url: root_path, method: :get, class: "box" do |f| %>
    <%= f.label :input, 'Search by song, lyric or artist' %>
    <%= f.text_field :input, class: "input my-2" %>

    <%= f.submit "Search", class: "btn btn-blue"%>
<% end %>


<% unless @result.nil? %>
  <ul class='m-3 p-3 md:overflow-auto md:h-2/5'>
    <% @result[:response][:hits].each do |hit| %>
      <li class='flex justify-between items-center my-3'>
        <small><%= link_to hit[:result][:full_title], hit[:result][:url] %></small>

        <%= form_with model: @song do |f| %>
            <%= f.hidden_field :image_url, value: hit[:result][:song_art_image_thumbnail_url] %>
            <%= f.hidden_field :lyrics_url, value: hit[:result][:url] %>
            <%= f.hidden_field :title, value: hit[:result][:title] %>
            <%= f.hidden_field :artist, value: hit[:result][:artist_names] %>
            <%= f.hidden_field :artist_url, value: hit[:result][:primary_artist][:url] %>
            <%= f.hidden_field :genius_id, value: hit[:result][:id] %>

            <% if @song.nil? %>
              <%= link_to 'Log in', new_user_session_path, class: 'btn-small btn-blue' %>
            <% else %>
              <%= f.submit "Add", class: "btn-small btn-blue" %>
            <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/songs/_song_form.html.erb
<%= form_with model: song, class: "box flex flex-col" do |f| %>

    <div class="flex justify-around">
      <%= f.label :title, class: "" %>
      <%= f.text_field :title, class: "input" %>
    </div>

    <div class="flex justify-around my-2">
      <%= f.label :artist, class: "" %>
      <%= f.text_field :artist, class: "input" %>
    </div>
    
    <%= f.submit "Save", class: "border btn btn-blue" %>
<% end %>

app/views/songs/_songlist.html.erb
<% if songs.empty? %>
  <p>No songs yet!</p>
<% else %>
  <% songs.each do |song| %>
    <% if song.user_id === current_user.id %>
      <%= turbo_frame_tag song do %>
        <li style='display: grid; grid-template-columns: 80% 20%' class="my-2">
        
          <p>
            <b><%=link_to song.title, song_path(song.id), data: {turbo_frame: '_top'} %></b> by
            <b><%= link_to song.artist, song.artist_url, data: {turbo_frame: '_top'} %></b>
          </p>

          <div class='flex justify-end items-center'>
            <%= link_to image_tag("edit.png", class:'w-4 mx-3'), edit_song_path(song.id) %>
            <%= link_to image_tag("x.png", class: 'w-4 mx-3'), song_path(song.id), data: {turbo_method: :delete} %> 
          </div>
          
        </li>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/songs/edit.html.erb
<%= turbo_frame_tag @song do %>
  <%= render "song_form", song: @song %>
<% end %>

app/views/songs/index.html.erb
<div class="md:center">  
  <%= render 'shared/greeting', current_user: current_user %>
  <div class="box">
    <h1 class="text-xl">Songs:</h1>
    <ul class="">
      <small>
        Sort by:
        <%= link_to 'Artist', root_path(sort: 'artist') %> •
        <%= link_to 'Recent', root_path(sort: 'recent') %> •
        <%= link_to 'Title', root_path(sort: 'title') %>
      </small>
  
      <% if defined?(@songs) %>
        <%= render 'songlist', {songs: @songs} %>
      <% else %>
        <p><%= link_to 'Log in', new_user_session_path %> to save songs!</p>
      <% end %>
    </ul>
  </div>
  
  <%= render 'search', result: @result %>

  </div>
</div>

app/views/songs/show.html.erb
<div class="flex flex-col">
  <h1 class='text-xl m-2 p-2'><%= link_to @song.title, @song.lyrics_url %> - <%= @song.artist %></h1>
  
  <div class="box"><%= simple_format(@song.lyrics, class: 'm-2 p-2') %></div>
</div>