config/routes.rb
Rails.application.routes.draw do
  root "songs#index"

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :songs, :places
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  # geocoded_by :place_id

  def info
    url = HTTParty.get("https://maps.googleapis.com/maps/api/place/details/json?place_id=#{place_id}&fields=current_opening_hours&key=#{ENV["GOOGLE_MAPS_KEY"]}",  format: :plain)
    JSON.parse url, symbolize_names: true
  end

  def open?(info)
    if info[:result][:current_opening_hours][:open_now] == true
      'OPEN'
    else
      'CLOSED'
    end
  end

  def hours(info)
    info[:result][:current_opening_hours][:weekday_text]
  end

  def distance_to(lat, long, place)
    response = HTTParty.get("https://maps.googleapis.com/maps/api/directions/json?origin=#{lat},#{long}&destination=place_id:#{place}&key=#{ENV["GOOGLE_MAPS_KEY"]}", format: :plain)
    info = JSON.parse response, symbolize_names: true
    info[:routes][0][:legs][0][:distance][:text]
  end

  def nearby(lat, long)
    response = HTTParty.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{lat}%2C#{long}&radius=1000&keyword=karaoke&key=#{ENV["GOOGLE_MAPS_KEY"]}", format: :plain)
    JSON.parse response, symbolize_names: true
  end

  def search(query)
    search = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{query}&key=#{ENV["GOOGLE_MAPS_KEY"]}", format: :plain)

    coordinates = JSON.parse search, symbolize_names: true

    return if coordinates[:results].first.nil?

    lat = coordinates[:results].first[:geometry][:location][:lat]
    long = coordinates[:results].first[:geometry][:location][:lng]

    response = HTTParty.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{lat}%2C#{long}&radius=1000&keyword=karaoke&key=#{ENV["GOOGLE_MAPS_KEY"]}", format: :plain)
    JSON.parse response, symbolize_names: true
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:destroy, :edit, :update, :show]

  def index
    @places = Place.all
    @place = Place.new
    @location = User.location(request.ip)
    @lat = @location[:latitude]
    @long = @location[:longitude]

    # @lat = '35.683502'
    # @long = '139.657684'

    @nearby = @place.nearby(@lat, @long)

    @search_results = @place.search(params[:search])
  end

  def new
    @place = Place.new
  end

  def show
    @map_url = "https://www.google.com/maps/embed/v1/place?q=place_id:#{@place.place_id}&key=#{ENV["GOOGLE_MAPS_KEY"]}"

    store_info = @place.info

    @status = @place.open?(store_info)
    @hours = @place.hours(store_info)
  end

  def create
    @place = current_user.places.build(place_params)

    redirect_to @place if @place.save
  end

  def edit
  end

  def update
    if @place.update(place_params)
      redirect_back_or_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place.destroy
    redirect_back_or_to root_path, status: :see_other
  end

  private

  def place_params
    params.require(:place).permit(:name, :user_id, :place_id, :lat, :lng)
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_nearby.html.erb
<div class="md:bg-white md:center md:p-6">
  <h1 class="m-2 text-xl">Nearby:</h1>
  
  <ul>
    <% unless nearby.nil? %>
      <% nearby[:results].each do |result| %>
        <div style='display: grid; grid-template-columns: 80% 20%' class='my-3 ml-1 flex justify-between items-center'>
  
          <li>
            <small><%= link_to result[:name], "https://www.google.com/maps/search/?api=1&query=karaoke&query_place_id=#{result[:place_id]}" %> -</small>
            <small><%= place.distance_to(lat, long, result[:place_id]) %></small>
          </li>
  
  
          <% if current_user.nil? %>
              <%= link_to 'Log in', new_user_session_path, class: 'btn-small btn-blue' %>
          <% else %>
            <%= form_with model: place do |f| %>
              <%= f.hidden_field :name, value: result[:name] %>
              <%= f.hidden_field :place_id, value: result[:place_id] %>
              <%= f.hidden_field :latitude, value: result[:geometry][:location][:lat] %>
              <%= f.hidden_field :longitude, value: result[:geometry][:location][:lng] %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.submit "Add", class: "btn-small btn-blue" %>
            <% end %>
          <% end %>
  
        </div>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/places/_placelist.html.erb
<h1 class='text-xl'>My Favorite Places</h1>

<ul>
  <% if current_user.nil? %>
    <p><%= link_to 'Log in', new_user_session_path %> to save places!</p>
  <% else %>
    <% current_user.places.each do |place| %>
      <%= turbo_frame_tag place do %>
        <li style='display: grid; grid-template-columns: 80% 20%'>
          <%= link_to place.name, place_path(place.id), data: {turbo_frame: '_top'} %> 

          <div class="flex justify-end items-center">
            <%= link_to image_tag("edit.png", class:'w-4 mx-3'), edit_place_path(place.id) %>
            <%= link_to image_tag("x.png", class: 'w-4 mx-3'), place_path(place.id), data: {turbo_method: :delete} %>
          </div>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/places/_search.html.erb
<ul> 
  <%= form_with url: places_path, method: :get, class: "my-2" do |f| %>
    <%= f.label :search, 'Search by zip code/name/address' %>
    <%= f.text_field :search, class: "input my-1" %>

    <%= f.submit "Search", class: "btn btn-blue" %>
  <% end %>

  <% unless result.nil? %>
    <% result[:results].each do |result| %>
      <div style='display: grid; grid-template-columns: 90% 10%' class='m-2'> 
        <li><%= link_to result[:name], "https://www.google.com/maps/search/?api=1&query=karaoke&query_place_id=#{result[:place_id]}" %></li>
        <%= form_with model: place do |f| %>
          <%= f.hidden_field :name, value: result[:name] %>
          <%= f.hidden_field :place_id, value: result[:place_id] %>
          <%= f.hidden_field :latitude, value: result[:geometry][:location][:lat] %>
          <%= f.hidden_field :longitude, value: result[:geometry][:location][:lng] %>
          <%= f.submit "Add", class: "btn-small btn-blue" %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/places/edit.html.erb
<%= turbo_frame_tag @place do %>
  <%= form_with model: @place, class: "box flex flex-col" do |f| %>

    <div class="flex justify-around">
      <%= f.label :name, class: "" %>
      <%= f.text_field :name, class: "input" %>
    </div>
    
    <%= f.submit "Save", class: "border btn btn-blue" %>
  <% end %>
<% end %>

app/views/places/index.html.erb
<div class="md:center">
  <%= render 'shared/greeting', current_user: current_user %>
  
  <div class="box">
    <%= render 'placelist' %>
  </div>
  
  <div class="box">
    <%= render "search", {result: @search_results, place: @place} %>
    <button class="hidden md:block btn btn-blue" onclick="toggleModal()">Show Nearby</button>
  </div>
  
  <div class="box md:hidden">
    <%= render 'nearby', {nearby: @nearby, lat: @lat, long: @long, place: @place } %>
  </div>

  <div class="modal hidden fixed z-50 w-full h-110 bg-opacity-5 bg-black flex-col justify-center items-center" onclick="toggleModal()">
    <%= render 'nearby', {nearby: @nearby, lat: @lat, long: @long, place: @place } %>
  </div>
</div>

app/views/places/show.html.erb
<div class="box">
  <h1 class='text-xl mb-2'><%= @place.name %></h1>

  <iframe
    width="100%"
    height="400px"
    style="border:0"
    loading="lazy"
    allowfullscreen
    src= <%= @map_url %>>
  </iframe>
</div>

<div class="box">
  <h1 class='text-xl mb-2'>Hours</h1>
  <%= @status %>
  <ul>
    <% @hours.each do |day| %>
      <li><%= day %></li>
    <% end %>
  </ul>
</div>